name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install root-level dependencies and run backend tests
      - name: Install dependencies and run tests
        run: |
          npm install  # Install dependencies from the root-level package.json
          npm test     # Run tests defined in the root-level package.json

      # Build frontend separately
      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build
