name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js for backend and frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies and run tests
      - name: Install dependencies and run tests
        run: |
          npm install
          npm test

      # Build frontend
      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build
