name: Local CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install backend dependencies and run tests
        working-directory: ./backend
        run: |
          npm install
          npm test

      - name: Install frontend dependencies and build
        working-directory: ./frontend
        run: |
          npm install
          npm run build
